sudo: false
language: c
 
addons:
  apt:
    packages:
    - pandoc

script:
  - curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

after_script:
  - cd greven/lumUI/.release
  - svn export https://github.com/zorker/rothui/trunk/wow8.0/rLib rLib
  - svn export https://github.com/zorker/rothui/trunk/wow8.0/rActionBar rActionBar
  - svn export https://github.com/zorker/rothui/trunk/wow8.0/rButtonTemplate rButtonTemplate
 
branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_success: never
    on_failure: always