sudo: false
language: c
 
addons:
  apt:
    packages:
    - pandoc

before_script:
  - mkdir temp
  - cd temp
  - svn export https://github.com/zorker/rothui/trunk/wow8.0/rLib rLib
  - svn export https://github.com/zorker/rothui/trunk/wow8.0/rActionBar rActionBar
  - svn export https://github.com/zorker/rothui/trunk/wow8.0/rButtonTemplate rButtonTemplate

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash
 
branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_success: never
    on_failure: always